<a href="https://colab.research.google.com/github/atakanberkyilmaz/Hafta1NumpyKutuphanesi/blob/main/Hafta_1_Numpy_K%C3%BCt%C3%BCphanesi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY Modülü
[Numpy.Org](https://numpy.org/)

In [ ]:
#Liste 2.1
import numpy as np


import komutu kütüphane ekler

In [ ]:
#Liste 2.2

iris=np.array([5.7,2.6,3.5,1.0])
print(iris)


In [ ]:
#Liste 2.3
print(np.array([[2,5,7]]))

In [ ]:
#Liste 2.4
print(np.array([[2,5,7], [3,6,8]]))

[[2 5 7]
 [3 6 8]]


In [ ]:
#Liste 2.5
print(np.zeros(3))

[0. 0. 0.]


In [ ]:
#Liste 2.6
print(np.zeros((4,3))) #boyut değerleri

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Liste 2.7
print(np.zeros((2,4,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#Liste 2.8
print(np.ones(4))

[1. 1. 1. 1.]


In [ ]:
#Liste 2.9
print(np.full((2,2),"Python"))

In [ ]:
#Liste 2.10
print(np.arange(0, 1, 0.2))

[0.  0.2 0.4 0.6 0.8]


In [ ]:
#Liste 2.11
print(np.linspace(0.0, 1.0, num=5))
print(np.linspace(0.0, 1.0, num=5, endpoint=False)) #bu aralıkta bana 5 tane eleman oluştur endpoint=false -> bitiş değerini alma

In [ ]:
#Liste 2.12
print(np.random.rand(2,2))
print(np.random.randn(2,2)) #random sayı  üretmek için kullanılan fonksiyon -> float değerinde

[[0.57414389 0.81594619]
 [0.93279523 0.78487526]]
[[ 0.80915877 -1.57626988]
 [ 0.3569506  -0.43604897]]


In [ ]:
#Liste 2.13
print(np.random.randint(3,7, size=(2, 4))) #integerlardan oluşan random sayılar

[[6 5 4 3]
 [4 5 4 3]]


In [ ]:
#Liste 2.14
dizi = np.arange(2.0, 9.0)
print(dizi.dtype,dizi)

float64 [2. 3. 4. 5. 6. 7. 8.]


In [ ]:
#Liste 2.15
dizi = np.arange(1, 3, dtype=np.int64)
print(dizi.itemsize)

8


In [ ]:
#Liste 2.16
dizi=np.arange(16)
print(dizi)
print("Boyut Sayısı:", dizi.ndim)
dizi.shape=(4,4)
print(dizi)
print("Boyut Sayısı:", dizi.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Boyut Sayısı: 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Boyut Sayısı: 2


In [ ]:
#Liste 2.17
dizi=np.array([[2,5,7], [3,6,8]])
print(dizi)
x=dizi.ravel()
print(x) #ravel dizileri tek boyuta indirmek için kullanılır

[[2 5 7]
 [3 6 8]]
[2 5 7 3 6 8]


In [ ]:
#Liste 2.18
dizi1 = np.array([4, 6, 8, 9])
dizi2 = np.array([2, 4, 3, 5])
print("Toplam  =", dizi1 + dizi2)
print("Fark  =", dizi1 - dizi2)
print("Çarpım  =", dizi1 * dizi2)
print("Bölüm (ondalık)  =", dizi1 / dizi2)
print("Bölüm (tam)  =", dizi1 // dizi2)
print("Bölümden kalan  =", dizi1 % dizi2)
print("Üst =", dizi1 ** dizi2)

Toplam  = [ 6 10 11 14]
Fark  = [2 2 5 4]
Çarpım  = [ 8 24 24 45]
Bölüm (ondalık)  = [2.         1.5        2.66666667 1.8       ]
Bölüm (tam)  = [2 1 2 1]
Bölümden kalan  = [0 2 2 4]
Üst = [   16  1296   512 59049]


In [ ]:
#Liste 2.19
dizi = np.array([[1, 2.5, 6], [8, 20, 11]])
for i in (dizi.min, dizi.max, dizi.sum, dizi.prod, dizi.std, dizi.var):
    print(i.__name__, "=", i())

min = 1.0
max = 20.0
sum = 48.5
prod = 26400.0
std = 6.274396828027022
var = 39.36805555555556


In [ ]:
#Liste 2.20
dizi = np.array([[1, 2.5, 6], [8, 20, 11]])
for i in (np.abs, np.sqrt, np.ceil, np.isnan):
    print("\n", i.__name__)
    print(i(dizi))


 absolute
[[ 1.   2.5  6. ]
 [ 8.  20.  11. ]]

 sqrt
[[1.         1.58113883 2.44948974]
 [2.82842712 4.47213595 3.31662479]]

 ceil
[[ 1.  3.  6.]
 [ 8. 20. 11.]]

 isnan
[[False False False]
 [False False False]]


In [ ]:
#Liste 2.21
dizi=np.array([5,12,4,-2,15,6,8,0])

In [ ]:
#Liste 2.22
print(dizi[4])
print(dizi[1:5])

15
[12  4 -2 15]


In [ ]:
#Liste 2.23
print(dizi[3:-1])

[-2 15  6  8]


In [ ]:
#Liste 2.24
print(dizi[:4])

[ 5 12  4 -2]


In [ ]:
#Liste 2.25
print(dizi[1::2])

[12 -2  6  0]


In [ ]:
#Liste 2.26
print(dizi[::-1]) #diziyi tersten yazdırmak için kullanılır

[ 0  8  6 15 -2  4 12  5]


In [ ]:
#Liste 2.27
dizi[2:4]=11
print(dizi)

[ 5 12 11 11 15  6  8  0]


In [ ]:
#Liste 2.28
dizi=np.array([5,12,4,-2,15,6,8,0])
print(dizi)
yeniDizi=dizi[2:4]
print(yeniDizi)
dizi[2]=200
print(yeniDizi)

[ 5 12  4 -2 15  6  8  0]
[ 4 -2]
[200  -2]


In [ ]:
#Liste 2.29
dizi=np.array([5,12,4,-2,15,6,8,0])
print(dizi)
yeniDizi=dizi[2:4].copy()
print(yeniDizi)
dizi[2]=200
print(yeniDizi)

[ 5 12  4 -2 15  6  8  0]
[ 4 -2]
[ 4 -2]


In [ ]:
#Liste 2.30
dizi=np.arange(12)
dizi.shape=(3,4)
print(dizi)
print(dizi[2,3])
print(dizi[0,:])
print(dizi[:,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
11
[0 1 2 3]
[ 2  6 10]


In [ ]:
#Liste 2.31
print(dizi[:,(0,2)])
print(dizi[(0,1),1:3])

[[ 0  2]
 [ 4  6]
 [ 8 10]]
[[1 2]
 [5 6]]


In [ ]:
#Liste 2.32
dizi=np.arange(12)
dizi.shape=(3,2,2)
print(dizi)
print(dizi[1,1,0])
print(dizi[1,:,0])

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
6
[4 6]


In [ ]:
#Liste 2.33
dizi1 = np.full((2,4), 0.0)
dizi2 = np.full((3,4), 1.0)
dizi3 = np.full((4,4), 2.0)
print(dizi1);print(dizi2);print(dizi3)
dizi4 = np.concatenate((dizi1, dizi2, dizi3), axis=0)
print(dizi4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [ ]:
#Liste 2.34
dizi1 = np.full((2,4), 0.0)
dizi2 = np.full((2,4), 1.0)
print(dizi1);print(dizi2)
dizi3 = np.concatenate((dizi1, dizi2), axis=1) #dizileri birleştirmeye yarar
print(dizi3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


In [ ]:
#Liste 2.35
dizi1= np.arange(12.0)
print(np.split(dizi1,4)) #diziyi bölmeye yarıyor


[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.]), array([ 9., 10., 11.])]
